**Generate Input Vector from Tweet**

In [1]:
import nltk
import numpy as np
np.set_printoptions(precision=3)

tweet = "A banana a day keeps the doctor away."
v = {'v0' : 'banana', 'v1' : 'chocolate', 'v2' : 'sweet', 'v3' : 'cookie'}
tweet_words = [word.lower() for word in nltk.word_tokenize(tweet) if word.isalpha()]
x = np.array([tweet_words.count(v[key]) for key in v.keys()])[np.newaxis]
print("Input Vector: ", x)

Input Vector:  [[1 0 0 0]]


**Layers of the network**

In [2]:
w1 = np.array([[0.5, 0.5, 0, 0], [1, 0.5, 0, 1]])
b1 = np.array([[0], [0]])
w2 = np.array([[0, -1], [1, -1]])
w3 = np.array([[1, 0.5],[1, 0.5], [0.5, 1]])

**Sigmoid Function**

In [3]:
def sigmoid(fx):
    return 1 / (1 + np.exp(-fx))

# This function defines a vectorized function which takes a nested sequence of objects or numpy arrays as inputs
# and returns an single or tuple of numpy array as output.
sigmoid_v = np.vectorize(sigmoid)

**Display y_predict corresponding to the output labels**

In [4]:
def network_output(y_pred):
    y = ['banana', 'cookie', 'other']
    output = "**Prediction**"
    for index1, index2 in zip(y, y_pred):
        output = output + "\n" + str(index1) + ": " + str(index2)
    return output

**Compute forward pass output**

In [6]:
from scipy.special import softmax

z1 = np.dot(w1, x.T) + b1
a1 = sigmoid_v(z1)
z2 = np.dot(w2, a1)
a2 = sigmoid_v(z2)
z3 = np.dot(w3, a2)
y_pred = softmax(z3)
print(network_output(y_pred))

**Prediction**
banana: [0.325]
cookie: [0.325]
other: [0.35]


**Correct Output Label**

In [7]:
y_true = np.array([[1], [0], [0]])

**Log Loss (Cross Entropy)**

In [9]:
from sklearn.metrics import log_loss

cce = log_loss(y_true, y_pred)
print("Cross Entropy/Log Loss: ", np.around(cce, 3))

Cross Entropy/Log Loss:  0.649


In [15]:
del3 = np.multiply(y_pred-y_true, y_pred*(np.array([[1], [1], [1]])-y_pred))
print(del3)

[[-0.148]
 [ 0.071]
 [ 0.08 ]]


In [27]:
del2 = np.multiply(np.array([[1], [1]])-a2, np.dot(w3.T, del3))
print(del2)

[[-0.025]
 [ 0.022]]


In [29]:
del1 = np.multiply(a1, np.dot(w2, del2))
print(del1)

[[-0.014]
 [-0.034]]


In [34]:
w3 = np.array([[1, 0.5],[1, 0.5], [0.5, 1]])
w3_new = w3 - np.gradient(w3)
print(w3_new)

w2 = np.array([[0, -1], [1, -1]])


w1 = np.array([[0.5, 0.5, 0, 0], [1, 0.5, 0, 1]])



[[[1.   0.5 ]
  [1.25 0.25]
  [1.   0.5 ]]

 [[1.5  1.  ]
  [1.5  1.  ]
  [0.   0.5 ]]]
