**Exercise 2**

In [1]:
import numpy as np
from scipy.special import softmax

np.set_printoptions(precision=3)

x = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]) # one-hot encoding of Kevin likes bananas

In [2]:
wi = np.array([[0, -1, 0], [-1, 0, 0.5]])
wh = np.array([[0, 1], [1, 0]])
wout = np.array([[-1, 1], [0, -1], [1, 0]])

In [3]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

In [4]:
a1 = np.add(np.dot(wi, np.array([x[0]]).T), np.dot(wh, sigmoid(np.dot(wi, np.array([x[0]]).T))))
softmax(np.dot(wout, a1))

array([[0.135],
       [0.482],
       [0.383]])

In [5]:
a2 = np.add(np.dot(wi, np.array([x[1]]).T), np.dot(wh, sigmoid(np.dot(wi, np.array([x[1]]).T))))
softmax(np.dot(wout, a2))

array([[0.611],
       [0.217],
       [0.172]])

In [6]:
a3 = np.add(np.dot(wi, np.array([x[2]]).T), np.dot(wh, sigmoid(np.dot(wi, np.array([x[2]]).T))))
softmax(np.dot(wout, a3))

array([[0.395],
       [0.1  ],
       [0.505]])

In [7]:
a = np.add(np.dot(wi, x), np.dot(wh, sigmoid(np.dot(wi, x))))
softmax(np.dot(wout, a))

array([[0.044, 0.203, 0.137],
       [0.155, 0.072, 0.035],
       [0.123, 0.057, 0.175]])

**Exercise 1**

In [19]:
input = 100
hidden_layer = 400
output = 5

In [20]:
# Elman RNN
total_parameters_elman = input*hidden_layer + hidden_layer + hidden_layer*hidden_layer + hidden_layer*output + output
total_parameters_elman

202405

In [21]:
# Jordan RNN
total_parameters_jordan = input*hidden_layer + hidden_layer + hidden_layer*output + output + output*hidden_layer
total_parameters_jordan

44405

**Exercise 3**

In [11]:
w_f = np.array([[0, -1, -1, 1, 0], [-1, 1, 0, -1, 1]])
w_i = np.array([[-1, 1, 0, 1, 0], [0, 1, 0, 1, -1]])
w_c = np.array([[-1, 0, 1, 1, 0], [-1, -1, 1, -1, 1]])
w_o = np.array([[-1, 0, 1, 1, 0], [0, 1, 1, -1, 1]])
w_out = np.array([[-1, 1], [0, -1], [0, 0]])

In [12]:
h1 = np.array([[0.370], [-0.123]])
c1 = np.array([[0.557], [-0.338]])

In [13]:
def column_concatenate(a, b):
    return np.concatenate((a, b), axis=None)[np.newaxis].T

In [14]:
f_t = sigmoid(np.dot(w_f, column_concatenate(h1, x[1]))) # bias vector zero
i_t = sigmoid(np.dot(w_i, column_concatenate(h1, x[1]))) # bias vector zero
c_tilde_t = np.tanh(np.dot(w_c, column_concatenate(h1, x[1])))
c_t = np.multiply(f_t, c1) + np.multiply(i_t, c_tilde_t)
o_t = sigmoid(np.dot(w_o, column_concatenate(h1, x[1])))
h_t = np.multiply(o_t, np.tanh(c_t))

In [15]:
y_t = np.dot(w_out, o_t)
y_t

array([[-0.407],
       [-0.245],
       [ 0.   ]])

In [16]:
softmax(y_t)

array([[0.272],
       [0.32 ],
       [0.409]])

**Output**

Output corresponds to: [p(VBZ), p(NNS), p(NNP)]

Therefore, output: NNP