**Input: I like tea**

In [1]:
import numpy as np
np.set_printoptions(precision=3)

x = np.array([[0, 1, 1, 0], [0, 0, 0, 1], [1, 1, 0, 0]]) # input sentence

**Load Parameters**

In [2]:
w1 = np.array([[0, 0, 0, -1], [-1, 1, 0, -1]])
w2 = np.array([[1, 0, -1, 1]])
w3 = np.array([[-1, 1, 0, 1]])
wo = np.array([[0, 0, 1], [0, 1, -1]])

**Sigmoid**

In [3]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

**First Feature Map**

In [4]:
fw1 = np.array([[np.sum(x[:2] * w1), np.sum(x[1:] * w1)]])
fw1.T

array([[-1],
       [-1]])

**Second Feature Map**

In [5]:
fw2 = np.array([[np.sum(x[0] * w2), np.sum(x[1] * w2), np.sum(x[2] * w2)]])
fw2.T

array([[-1],
       [ 1],
       [ 1]])

**Third Feature Map**

In [6]:
fw3 = np.array([[np.sum(x[0] * w3), np.sum(x[1] * w3), np.sum(x[2] * w3)]])
fw3.T

array([[1],
       [1],
       [0]])

**Max Pooling Output**

In [7]:
from scipy.special import softmax

mpv = np.array([[np.amax(sigmoid(fw1)), np.amax(sigmoid(fw2)), np.amax(sigmoid(fw3))]]) # max pool vector
mpv.T

array([[0.269],
       [0.731],
       [0.731]])

**Output: Positive; Negative**
I guess, this network is trying to determine positive or negative emotions

In [8]:
softmax(np.dot(wo, mpv.T))

array([[0.675],
       [0.325]])